default:
  image: registry.gitlab.com/bildungslogin/lizenzmanager

stages:
  - build

build-packages:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/bildungslogin-plugin
    - dpkg-buildpackage
    - cd $CI_PROJECT_DIR/python-bildungslogin
    - dpkg-buildpackage
    - cd $CI_PROJECT_DIR/udm-bildungslogin
    - dpkg-buildpackage
    - cd $CI_PROJECT_DIR/ucs-school-umc-licenses
    - dpkg-buildpackage
  artifacts:
    paths:
      - ./*.deb
      - ./*.changes
      - ./*.buildinfo
      - ./*.dsc
  only:
    - main
