default:
  image: registry.gitlab.com/bildungslogin/lizenzmanager

stages:
  - build

build-packages:
  stage: build
  script:
    - cd $CI_PROJECT_DIR/bildungslogin-plugin
    - dpkg-buildpackage
    - cd $CI_PROJECT_DIR/python-bildungslogin
    - dpkg-buildpackage
    - cd $CI_PROJECT_DIR/udm-bildungslogin
    - dpkg-buildpackage
    - cd $CI_PROJECT_DIR/ucs-school-umc-licenses
    - dpkg-buildpackage
    - cd $CI_PROJECT_DIR
    - python rename_packages.py
    - mkdir -p ucs_4.4-0-bildungslogin/all/ && mv *.deb ucs_4.4-0-bildungslogin/all/
    - dpkg-scanpackages . > Packages
    - mv ucs_4.4-0-bildungslogin/all/* .
    - gzip -9c Packages > Packages.gz
    - python build_release.py
  artifacts:
    paths:
      - ./*.deb
      - ./Packages*
      - ./Release
  only:
    - main
