stages:
  - lint
  # build stages will be dynamically added

.lint:
  stage: lint
  image:
    name: $LINT:$UCS_VERSION
    entrypoint: [""]
  script:
    - ucslint -j ucslint.xml $base
  artifacts:
    reports:
      junit: ucslint.xml

.deb:
  variables:
    GIT_STRATEGY: none  # disables `git clone` altogether
  image:
    name: $SSH
    entrypoint: [""]
  before_script:
    - chmod 0600 "$SSH_PRIVATE_KEY"
    - md5sum $SSH_PRIVATE_KEY
  script:
    - |
      set -x && ssh -i "$SSH_PRIVATE_KEY" \
        -o BatchMode=yes \
        -l build \
        $IMPORT_HOST \
        repo_admin.py \
          -G $CI_REPOSITORY_URL \
          -p $base \
          -b $BRANCH \
          -P $base \
          -s $SCOPE \
          -r ${UCS_RELEASE}-0-0
    - |
      set -x && ssh -i "$SSH_PRIVATE_KEY" \
        -o BatchMode=yes \
        -l build \
        $BUILD_HOST \
        build-package-ng \
          --no-pbuilder-update \
          -P ucs \
          -p $base \
          -s $SCOPE \
          -r ${UCS_RELEASE}-0-0
