70bildungslogin-plugin.inst  usr/lib/univention-install/
30bildungslogin-plugin.uinst usr/lib/univention-uninstall/
bildungslogin_plugin var/lib/univention-appcenter/apps/ucsschool-apis/data/plugins/bildungslogin-plugin/
opa var/lib/univention-appcenter/apps/ucsschool-apis/data/plugins/bildungslogin-plugin/
pyproject.toml var/lib/univention-appcenter/apps/ucsschool-apis/data/plugins/bildungslogin-plugin/
