#!/usr/share/ucs-test/runner bash
## desc: In-container unit tests
## exposure: safe
## tags: [bildungslogin]
## packages: [bildungslogin-plugin]

APP="ucsschool-apis"
CMD="cd /var/lib/univention-appcenter/apps/$APP/data/plugins/bildungslogin-plugin/; python3 -m pytest -lvvx --cov=bildungslogin_plugin --cov-report= tests/unittests"

echo "Running in container: sh -c \"$CMD\""

univention-app shell "$APP" sh -c "$CMD"
