#!/bin/sh

# Copyright 2021 Univention GmbH
#
# http://www.univention.de/
#
# All rights reserved.
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# Binary versions of this program provided by Univention to you as
# well as other copyrighted, protected or trademarked materials like
# Logos, graphics, fonts, specific documentations and configurations,
# cryptographic keys etc. are subject to a license agreement between
# you and Univention and not subject to the GNU AGPL V3.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

if grep -q deb.debian.org /etc/apt/sources.list; then
  echo "Setting Debian repository to 141.76.2.4 (ftp.de.debian.org) in 'ucsschool-apis' Docker container..."
  mv -v /etc/apt/sources.list /etc/apt/sources.list.ori
  echo '# Hard coded german Debian mirror to make life easier for firewall admins.
# 141.76.2.4 -> ftp.de.debian.org
deb http://141.76.2.4/debian buster main
deb http://141.76.2.4/debian buster-updates main
deb http://141.76.2.4/debian-security buster/updates main
' > /etc/apt/sources.list
fi

echo "Installing 'default-jre' Debian package..."
apt update
apt install default-jre

echo "Generating OpenAPI client for the UDM REST API..."
update_openapi_client \
  --generator java \
  --jar /var/lib/univention-appcenter/apps/ucsschool-apis/data/plugins/bildungslogin-plugin/openapi-generator-cli-5.0.0.jar \
  --insecure \
  --username  "$(hostname -s)\$" \
  --password "$(cat /etc/machine.secret)" \
  "$LDAP_MASTER"
